### PR TITLE
Responsivity overhaul all over the site

### PR DESCRIPTION
**Pull request by codyml**
I looked at every page I could think of and made whatever changes were necessary to make Lacuna look okay on screens down to 320px.  You'll need to revert features to get the People page to work.

### CODE REVIEW

**Comment by mwidner** [comment]
Looks pretty good, except that now the Lacuna logo is huge in a regular browser window. 
screen shot 2016-12-05 at 11 51 27 am

Also, when the menus are resized, we start to see the menu title (i.e., "Institutional Menu"). Will you look to see if there's a way to change that behavior?

**Comment by codyml** [comment]
@mwidner I can't reproduce the huge logo on my side, but that could be happening if you haven't cleared a cache since checking the logo PR  —  maybe the new big logo image may be being used but the CSS to manage its size might not be activated?  And I'm a little confused about your last comment; what's going on with the menu titles?

**Comment by mwidner** [comment]
@codyml When you go to, say, a phone-sized width, you'll see that the menu becomes a single drop-down with its name (like "institutional menu"). Does that make sense?

I guess the huge logo may have been a caching issue. It looks like its gone for me now.

**Comment by codyml** [comment]
@mwidner Yep it becomes a <select> element, what would you like it to do instead?

**Comment by mwidner** [comment]
Hmm... well, maybe instead of having a textual name, it could just become the standard hamburger menu (https://en.wikipedia.org/wiki/Hamburger_button)?

**Comment by codyml** [comment]
@mwidner Ok, would you like it to still bring up that same \<select\>-style mobile menu?

**Comment by mwidner** [comment]
Yeah, we still want the mobile menu, I just don't want it to have a name if that's possible. Thanks!

**Comment by codyml** [comment]
K you got it!

**Comment by codyml** [comment]
How does this look?

screen shot 2016-12-06 at 5 19 50 pm

**Pull request merged**
